/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package journal.event.reader.samples;

import journal.event.reader.JournalReader;
import journal.event.reader.JournalReaderFactory;

public class App {

    public static void main(String[] args) {
        InputEventBufferReader bufferReader = new InputEventBufferReader();

        JournalReader<InputEvent> journalReader = JournalReaderFactory.createJournalReader(bufferReader);

        journalReader.setHandler(new InputEventHandler());

        InputEvent event1 = journalReader.getNextEvent();
        InputEvent event2 = journalReader.getNextEvent();

        System.out.println("Ask: " + event1.ask + " Bid: " + event1.bid);
        System.out.println("Ask: " + event2.ask + " Bid: " + event2.bid);

        journalReader.replay();
    }
}